# ~/.config/helix/config.toml

theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
true-color = true
color-modes = true
cursorline = true
auto-save = true
idle-timeout = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "file-name", "spinner"]
center = ["diagnostics"]
right = ["position", "file-type"]
separator = "â”‚"

[editor.lsp]
display-messages = true

[keys.insert]
j = { k = "normal_mode"}
